import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeroUiProvider } from "./providers/Herouiproviders";
import { AuthProvider } from "./context/AuthContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zero One Forge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <HeroUiProvider>
        <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              style: {
                fontSize: "14px",
                fontWeight: 400,
              },

              success: {
                style: {
                  color: "#03A822",
                },
              },
              error: {
                style: {
                  color: "#FD4755",
                },
              },
            }}
          />
          <AuthProvider>
          {children}
          </AuthProvider>
          </HeroUiProvider>
      </body>
    </html>
  );
}
